export const choiceGrp = [
  "Division",
  "RequestType",
  "MerchLocation",
  "PreTicketed",
  "MARSDepartment",
  "MerchType",
  "DCOptions",
  "DCPhysicallyReTicketed",
  "ReasonForReject",
  "FCOptions",
];

export const lookupGrp = [
  {
    key: "DistributionCenter",
    value: "DistributionCenter",
  },
];

export const productPanel = [
  "Division",
  "RequestType",
  "DistributionCenter",
  "MerchLocation",
];

export const validations = {
  numberOnly: /^[0-9]+$/,
  numberOnlylenEight: /^[0-9]{8}$/,
  numberOnlylenFour: /^[0-9]{4}$/,
  numberOnlylenSix: /^[0-9]{6}$/,
  alhpaNumericlenFour: /^[a-zA-Z0-9]{4}$/,
  numberGrtrZero: /^[1-9][0-9]*$/,
  numbersOnlyWithNegative: /^-?\d+(\.\d+)?$/,
  floatAndCurrencyRegex: /^-?\d*(\.\d+)?$|^-?\$\d{1,3}(,\d{3})*(\.\d+)?$/,
  mm_yy_Only: /^(0[1-9]|1[0-2])\/\d{2}$/,
};

export const ReqForm_AllFeilds = {
  Division: false,
  RequestType: false,
  DistributionCenter: false,
  MerchLocation: false,
  PONumber: false,
  UnitsPerPlanning: false,
  LadderPlan: false,
  Page: false,
  Line: false,
  MARSDepartment: false,
  Vendor: false,
  VendorName: false,
  MARSCategory: false,
  NBCStyle: false,
  MerchType: false,
  Cost: false,
  CompareAt: false,
  Retail: false,
  ULine: false,
  PreTicketed: false,
  ControlFiles: false,
  MarsStyleChange: false,
  MARSDescription: false,
  SpecialInstructions: false,
  NewMARSDepartment: false,
  NewVendor: false,
  NewVendorName: false,
  NewMARSCategory: false,
  NewNBCStyle: false,
  NewMerchType: false,
  NewCost: false,
  NewCompareAt: false,
  NewRetail: false,
  NewULine: false,
  SubmitToPlanningMgr: false,
  UpdatedPC: false,
  MerchPrimaryApproverId: false,
  MerchSecondaryApproverId: false,
  MerchSign: false,
  MerchSignDate: false,
  MerchManagerApproved: false,
  MerchManagerSign: false,
  MerchManagerSignDate: false,
  DCUnitsActedOn: false,
  DCWorkCompletedByTitle: false,
  DCWorkCompletedById: false,
  DCOptions: false,
  OverAllRetailImpact: false,
  DCOptionComments: false,
  PrintMARS: false,
  DCApproved: false,
  DCArchived: false,
  DCReject: false,
  DCPhysicallyReTicketed: false,
  ReasonForReject: false,
  DCComments: false,
  DCSign: false,
  DCSignDate: false,
  DCApproverEmail: false,
};

export const ReqCheckBox_NonReq = [
  "MarsStyleChange",
  "MerchManagerApproved",
  "PrintMARS",
  "DCApproved",
  "DCArchived",
  "DCReject",
];

export const Req_DcPanel = [
  "DCUnitsActedOn",
  "DCProcessed",
  "DCUnProcessed",
  "DCWorkCompletedById",
  "DCOptions",
  "OverAllRetailImpact",
  "DCOptionComments",
  "PrintMARS",
  "DCApproved",
  "DCArchived",
  "DCReject",
  "DCPhysicallyReTicketed",
  "ReasonForReject",
  "DCComments",
  "DCSign",
  "DCSignDate",
  "DCApproverEmail",
];

export const LocInquiry_AllFeilds = [
  "Division",
  "RequestType",
  "DistributionCenter",
  "MerchLocation",
  "PONumber",
  "UnitsPerPlanning",
  "LadderPlan",
  "Page",
  "Line",
  "MARSDepartment",
  "Vendor",
  "VendorName",
  "MARSCategory",
  "NBCStyle",
  "MerchType",
  "Cost",
  "CompareAt",
  "Retail",
  "ULine",
  "PreTicketed",
  "ControlFiles",
  "MarsStyleChange",
  "MARSDescription",
  "SpecialInstructions",
];

export const LocInquiry_Req = [
  "Division",
  "RequestType",
  "DistributionCenter",
  "MerchLocation",
  "MARSDepartment",
  "Vendor",
  "Cost",
  "Retail",
  "NBCStyle",
  "MerchType",
  "MARSCategory",
  "MARSDescription",
  "SpecialInstructions",
];

export const LocInquiry_Disable = [
  "PONumber",
  "LadderPlan",
  "Page",
  "Line",
  "VendorName",
  "CompareAt",
  "ULine",
  "PreTicketed",
  "MarsStyleChange",
];
