export const FcOriginalInfo = [
  {
    label: "TRX",
    req: false,
    name: "FCTRX",
    disabled: false,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Code",
    req: false,
    name: "FCCode",
    disabled: false,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Department",
    req: false,
    name: "MARSDepartment",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Vendor #",
    req: false,
    name: "Vendor",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Category",
    req: false,
    name: "MARSCategory",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Purchase Order",
    req: false,
    name: "PONumber",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "NBC Style",
    req: false,
    name: "NBCStyle",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Merch Type",
    req: false,
    name: "MerchType",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Cost($)",
    req: false,
    name: "Cost",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Retail($)",
    req: false,
    name: "Retail",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Header",
    req: false,
    name: "MARSHeaderSuffix",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Suffix",
    req: false,
    name: "Suffix",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {},
  {},
  {},
];

export const FcNewOriginalInfo = [
  {
    label: "TRX",
    req: false,
    name: "FCNewTRX",
    disabled: false,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Code",
    req: false,
    name: "FCNewCode",
    disabled: false,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Department",
    req: false,
    name: "NewMARSDepartment",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Vendor #",
    req: false,
    name: "NewVendor",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Category",
    req: false,
    name: "NewMARSCategory",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "NBC Style",
    req: false,
    name: "NewNBCStyle",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Merch Type",
    req: false,
    name: "NewMerchType",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Cost($)",
    req: false,
    name: "NewCost",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Retail($)",
    req: false,
    name: "NewRetail",
    disabled: true,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {},
];
