import { IErrMsgs } from "../Interfaces/IMarsForm";
import { validations } from "./Constants";

export const OriginalInfo = [
  {
    label: "Master PO#",
    name: "PONumber",
    reqValid: validations.numberOnlylenSix,
    placeholder: "Exactly 6 numbers",
    type: "text",
    MaxLen: 6,
  },
  {
    label: "Units Per Planning",
    name: "UnitsPerPlanning",
    reqValid: false,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Earliest Ladder Plan",
    name: "LadderPlan",
    reqValid: validations.mm_yy_Only,
    placeholder: "Enter MM/YY",
    type: "text",
    MaxLen: 5,
  },
  {
    label: "Page",
    name: "Page",
    reqValid: false,
    placeholder: "Enter Max 2 digits",
    type: "text",
    MaxLen: 2,
  },
  {
    label: "Line",
    name: "Line",
    reqValid: false,
    placeholder: "Enter Max 2 digits",
    type: "text",
    MaxLen: 2,
  },
  {
    label: "Department",
    name: "MARSDepartment",
    reqValid: false,
    placeholder: "Select Departmant",
    type: "select",
    options: "MARSDepartment",
  },
  {
    label: "Vendor #",
    name: "Vendor",
    reqValid: validations.alhpaNumericlenFour,
    placeholder: "Enter 4 chars/numbers",
    type: "text",
    MaxLen: 4,
  },
  {
    label: "Vendor Name",
    name: "VendorName",
    reqValid: false,
    placeholder: "Enter Vendor Name",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Category",
    name: "MARSCategory",
    reqValid: validations.numberOnlylenFour,
    placeholder: "Exactly 4 numbers",
    type: "text",
    MaxLen: 4,
  },
  {
    label: "NBC Style",
    name: "NBCStyle",
    reqValid: validations.numberOnlylenSix,
    placeholder: "Exactly 6 numbers",
    type: "text",
    MaxLen: 6,
  },
  {
    label: "Merch Type",
    name: "MerchType",
    reqValid: false,
    placeholder: "Enter exactly 6 numbers",
    type: "select",
    options: "MerchType",
  },
  {
    label: "Cost($)",
    name: "Cost",
    reqValid: validations.floatAndCurrencyRegex,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Compare At($)",
    name: "CompareAt",
    reqValid: validations.floatAndCurrencyRegex,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Retail($)",
    name: "Retail",
    reqValid: validations.floatAndCurrencyRegex,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "U-line",
    name: "ULine",
    reqValid: false,
    placeholder: "Marshalls U-Line Required",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "PreTicketed ?",
    name: "PreTicketed",
    reqValid: false,
    placeholder: "Select PreTicketed",
    type: "select",
    options: "PreTicketed",
  },
  {
    label: "Did you check control files AC/MC495a ?",
    name: "ControlFiles",
    reqValid: false,
    placeholder: "",
    type: "checkbox",
  },
  {
    label: "Is it a style change? (Prior FC approval needed)",
    name: "MarsStyleChange",
    reqValid: false,
    placeholder: "",
    type: "checkbox",
  },
  {},
  {},
];

export const NewInformation = [
  {
    label: "Department",
    name: "NewMARSDepartment",
    reqValid: false,
    placeholder: "Select Departmant",
    type: "select",
    options: "MARSDepartment",
  },
  {
    label: "Vendor #",
    name: "NewVendor",
    reqValid: validations.alhpaNumericlenFour,
    placeholder: "Enter 4 chars/numbers",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Vendor Name",
    name: "NewVendorName",
    reqValid: false,
    placeholder: "Enter Vendor Name",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Category",
    name: "NewMARSCategory",
    reqValid: validations.numberOnlylenFour,
    placeholder: "Exactly 4 numbers",
    type: "text",
    MaxLen: 4,
  },
  {
    label: "NBC Style",
    name: "NewNBCStyle",
    reqValid: validations.numberOnlylenSix,
    placeholder: "Exactly 6 numbers",
    type: "text",
    MaxLen: 6,
  },
  {
    label: "Merch Type",
    name: "NewMerchType",
    reqValid: false,
    placeholder: "Enter exactly 6 numbers",
    type: "select",
    options: "MerchType",
  },
  {
    label: "Cost($)",
    name: "NewCost",
    reqValid: validations.floatAndCurrencyRegex,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Compare At($)",
    name: "NewCompareAt",
    reqValid: validations.floatAndCurrencyRegex,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "Retail($)",
    name: "NewRetail",
    reqValid: validations.floatAndCurrencyRegex,
    placeholder: "",
    type: "text",
    MaxLen: 256,
  },
  {
    label: "U-line",
    name: "NewULine",
    reqValid: false,
    placeholder: "Marshalls U-Line Required",
    type: "text",
    MaxLen: 256,
  },
];

export const ReTicket_Req = [
  "Division",
  "RequestType",
  "DistributionCenter",
  "MerchLocation",
  "PONumber",
  "LadderPlan",
  "MARSDepartment",
  "Vendor",
  "NBCStyle",
  "MerchType",
  "Cost",
  "MARSCategory",
  "CompareAt",
  "Retail",
  "ControlFiles",
  "MARSDescription",
  "NewVendor",
  "NewNBCStyle",
  "NewCost",
  "NewRetail",
  "NewCompareAt",
  "NewMARSDepartment",
  "NewMARSCategory",
  "NewMerchType",
  "SubmitToPlanningMgr",
  "UpdatedPC",
  "MerchPrimaryApproverId",
  "MerchSecondaryApproverId",
  "MerchSign",
  "MerchSignDate",
];

export const ReTicket_AllFeilds = [
  "Division",
  "RequestType",
  "DistributionCenter",
  "MerchLocation",
  "PONumber",
  "UnitsPerPlanning",
  "LadderPlan",
  "Page",
  "Line",
  "MARSDepartment",
  "Vendor",
  "VendorName",
  "MARSCategory",
  "NBCStyle",
  "MerchType",
  "Cost",
  "CompareAt",
  "Retail",
  "ULine",
  "PreTicketed",
  "ControlFiles",
  "MarsStyleChange",
  "MARSDescription",
  "SpecialInstructions",
  "NewVendor",
  "NewVendorName",
  "NewMARSCategory",
  "NewNBCStyle",
  "NewCost",
  "NewRetail",
  "NewCompareAt",
  "NewMARSDepartment",
  "NewMerchType",
  "NewULine",
  "SubmitToPlanningMgr",
  "UpdatedPC",
  "MerchPrimaryApproverId",
  "MerchSecondaryApproverId",
  "MerchSign",
  "MerchSignDate",
];

export const ErrMsgs: IErrMsgs = {
  PONumber: "No more than 6 digits.",
  LadderPlan: "Must be exactly MM/YY.",
  Vendor: "Enter exactly 4 Chars/Numbers.",
  NBCStyle: "Enter exactly 6 numbers.",
  NewVendor: "Enter exactly 4 Chars/Numbers.",
  NewNBCStyle: "Enter exactly 6 numbers.",
  Cost: "Enter Numbers only.",
  CompareAt: "Enter Numbers only.",
  Retail: "Enter Numbers only.",
  MARSCategory: "Enter exactly 4 Numbers",
};
